# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Build & Publish to Github Pages Branch

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 14.x
      uses: actions/setup-node@v4
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Deploy to GitHub Pages Branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:pmalmsten/tension-wrench.git
        BRANCH: gh-pages
        FOLDER: build
        SSH_PRIVATE_KEY: ${{ secrets.AUTOPUBLISH_DEPLOY_PRIVATE_KEY }}
